version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    restart: unless-stopped
